# This workflow uploads a Python package to PyPI using Trusted Publishers
# Docs: https://docs.pypi.org/trusted-publishers/using-a-publisher/

name: Upload Python Package

on:
  release:
    types: [created]

  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      # ✅ Publish using PyPI Trusted Publisher (no secrets required)
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
